// Added comments to test the feature branch

public with sharing class Caliculator {
    public Caliculator() {
        // It's a public method
    }

    public Integer addition(Integer a, Integer b){
        return a+b;
    }

    // parameters changed
    public Integer substration(Integer a, Integer c){
        return a-c;
    }

    public Integer multipliacation(Integer a, Integer b){
        return a*b;
    }
}
